name: Build PX4 FMUv3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install PX4 dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git cmake build-essential ninja-build exiftool
        sudo apt install -y gcc-arm-none-eabi g++-arm-none-eabi
        pip3 install empy toml numpy jinja2 pyserial packaging

    - name: Build PX4 firmware
      run: |
        bash ./Tools/setup/ubuntu.sh
        make px4_fmu-v3_default
