name: Build Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # إذا كنت تستخدم GitHub Runner الرسمي اكتب: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc g++  # غيّر هذا حسب متطلبات مشروعك

      - name: Build project
        run: |
          make  # أو أي أمر بناء تستخدمه مثل ./waf configure && ./waf build

      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            build/     # عدّل هذا المسار حسب مجلد الإخراج لديك
