- name: Install ARM GCC Toolchain
  run: |
    wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
    tar -xjf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
    sudo mv gcc-arm-none-eabi-10.3-2021.10 /opt/
    echo "/opt/gcc-arm-none-eabi-10.3-2021.10/bin" >> $GITHUB_PATH
