name: Build PX4 FMUv3 with inverted roll

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-jinja2 ninja-build exiftool build-essential ccache
          sudo pip3 install pyserial empy toml numpy pandas jinja2 pyyaml

      - name: Clone and Setup PX4 Toolchain
        run: |
          sudo apt install -y cmake python3 python3-pip git wget
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          tar -xjf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          export PATH=$PWD/gcc-arm-none-eabi-10-2020-q4-major/bin:$PATH

      - name: Build Firmware
        run: |
          bash ./Tools/setup/ubuntu.sh --no-nuttx
          make px4_fmu-v3_default
