name: PX4 Firmware Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout PX4 Firmware
      uses: actions/checkout@v3

    - name: Install APT dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3 python3-pip python3-dev python3-setuptools python3-wheel \
          g++ gcc make cmake ninja-build ccache gfortran \
          git wget curl zip unzip tar \
          exiftool libxml2-utils libncurses5-dev libpython3-dev \
          gcc-arm-none-eabi gdb-arm-none-eabi \
          python3-jinja2 python3-numpy python3-empy python3-toml \
          python3-pandas python3-yaml python3-serial python3-pyparsing \
          python3-cerberus python3-kconfiglib

    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        pip3 install \
          empy toml numpy pandas jinja2 pyserial \
          pyyaml cerberus kconfiglib pyulog \
          packaging wheel pyparsing future pyros-genmsg

    - name: Build PX4 Firmware
      run: |
        make px4_fmu-v3_default
