name: Build PX4 firmware with inverted roll

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout PX4 source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3 python3-pip python3-dev python3-setuptools python3-wheel \
            git wget curl zip unzip tar cmake ninja-build build-essential \
            gcc-arm-none-eabi gdb-arm-none-eabi \
            python3-jinja2 python3-numpy python3-empy python3-toml \
            python3-pandas python3-yaml python3-serial python3-pyparsing \
            python3-cerberus python3-kconfiglib

      - name: Install Python packages
        run: |
          python3 -m pip install --upgrade pip
          pip3 install \
            empy toml numpy pandas jinja2 pyserial pyyaml \
            cerberus kconfiglib pyulog packaging wheel

      - name: Build PX4 firmware
        run: |
          make px4_fmu-v3_default

      - name: Upload PX4 firmware as artifact
        uses: actions/upload-artifact@v3
        with:
          name: px4_fmu-v3_firmware
          path: build/px4_fmu-v3_default/px4_fmu-v3_default.px4
